title: "Análise Mahout-Spark"
author: ""
date: "25-08-2015"
output: html_document
---

Análise Mahout utilizando Spark, para as entradas de 10, 25, 50, 100M utilizando 0, 1, 2, 3 e 7 slaves. 


```{r}
# Carrregando bibliotecas
library(dplyr)
library(ggplot2)

# Carregando dados
data <- read.csv("~/Projetos/AnaliseDSL/spark-mahout.csv")

# Transformando em númerico
data$time_in_minute <- as.numeric(gsub(",", ".", data$time_in_minute))
data$time_in_hour <- as.numeric(gsub(",", ".", data$time_in_hour))

# Agrupando por input size e slaves
by_input_slaves <- group_by(data, input_size,slaves)

# Análise do tempo em segundos
data_bySec <- summarise(by_input_slaves, mean(time_in_second))
colnames(data_bySec) <- c("input_size","slaves","time_in_second")
data_bySec$input_size <- as.factor(data_bySec$input_size)
data_bySec$slaves <- as.factor(data_bySec$slaves)

# Carregando gráfico
ggplot(data=data_bySec, aes(x=slaves, y=time_in_second, group=input_size, colour=input_size)) +
  geom_line() + 
  geom_point()

#data <- filter(data, input_size < 100) 

# Em minutos 

data_byMin <- summarise(by_input_slaves, mean(time_in_minute))
colnames(data_byMin) <- c("input_size","slaves","time_in_minute")
data_byMin$slaves <- as.factor(data_byMin$slaves)
data_byMin$input_size <- as.factor(data_byMin$input_size)

ggplot(data=data_byMin, aes(x=slaves, y=time_in_minute, group=input_size, colour=input_size)) +
  geom_line() + 
  geom_point() +
  coord_cartesian(ylim = c(0, 550))  +
  theme(panel.background=element_blank())
```


```{r}
# Carregando dados
dsl <- read.csv("~/Projetos/AnaliseDSL/dsl.csv")

# Transformando em númerico
dsl$time_in_minute <- as.numeric(gsub(",", ".", dsl$time_in_minute))
dsl$time_in_hour <- as.numeric(gsub(",", ".", dsl$time_in_hour))

# Agrupando por input size e slaves
by_input_slaves_dsl <- group_by(dsl, input_size,slaves)

# Análise do tempo em segundos
data_bySec_dsl <- summarise(by_input_slaves_dsl, mean(time_in_second))
colnames(data_bySec_dsl) <- c("input_size","slaves","time_in_second")
data_bySec_dsl$input_size <- as.factor(data_bySec_dsl$input_size)
data_bySec_dsl$slaves <- as.factor(data_bySec_dsl$slaves)

# Carregando gráfico
ggplot(data=data_bySec_dsl, aes(x=slaves, y=time_in_second, group=input_size, colour=input_size)) +
  geom_line() + 
  geom_point()

# Em minutos 
data_byMin_dsl <- summarise(by_input_slaves_dsl, mean(time_in_minute))
colnames(data_byMin_dsl) <- c("input_size","slaves","time_in_minute")
data_byMin_dsl$slaves <- as.factor(data_byMin_dsl$slaves)
data_byMin_dsl$input_size <- as.factor(data_byMin_dsl$input_size)

ggplot(data=data_byMin_dsl, aes(x=slaves, y=time_in_minute, group=input_size, colour=input_size)) +
  geom_line() + 
  geom_point() + 
  coord_cartesian(ylim = c(0, 550))  +
  theme(panel.background=element_blank())


```